import { Suggestion } from './types';

export const INITIAL_SUGGESTIONS: Suggestion[] = [
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    reference_id: 'DSB-2026-7F3K9P',
    title: 'Install Pedestrian Crossing at 5th and Main',
    description: 'Traffic has increased significantly. Need a marked crosswalk with pedestrian lights.',
    category: 'Roads & Footpaths',
    location_text: '5th Ave & Main St',
    status: 'under_review',
    support_count: 24,
    is_anonymous: false,
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 'c9a646d3-9c61-4cd7-9f51-75e964b96b7e',
    reference_id: 'DSB-2026-9B4X2T',
    title: 'Repair Broken Streetlights on Oak Lane',
    description: 'Three consecutive streetlights are out, creating safety concerns at night.',
    category: 'Street Lighting',
    location_text: 'Oak Lane between 2nd and 4th',
    status: 'planned',
    support_count: 42,
    is_anonymous: false,
    created_at: '2026-03-02T14:30:00Z',
  },
  {
    id: 'b5e86a01-2f78-4db8-8316-24838b93198e',
    reference_id: 'DSB-2026-5K1L8Q',
    title: 'Community Garden Composting Station',
    description: 'Add public compost bins in Riverside Park to reduce organic waste.',
    category: 'Waste Management',
    location_text: 'Riverside Park, North Section',
    status: 'implemented',
    support_count: 67,
    is_anonymous: true,
    created_at: '2026-02-20T09:15:00Z',
  },
  {
    id: 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
    reference_id: 'DSB-2026-8H2C6Y',
    title: 'Upgrade Playground Lighting',
    description: 'Improve solar illumination at Elmwood Playground.',
    category: 'Public Spaces',
    location_text: 'Elmwood Park',
    status: 'under_review',
    support_count: 15,
    is_anonymous: false,
    created_at: '2026-03-03T11:00:00Z',
  },
  {
    id: 'd4e5f6a1-b2c3-4d5e-8f9a-0b1c2d3e4f5a',
    reference_id: 'DSB-2026-3M7N2P',
    title: 'Pothole Repair on 12th Avenue',
    description: 'Large potholes damaging vehicles near the transit junction.',
    category: 'Roads & Footpaths',
    location_text: '12th Ave near Transit Hub',
    status: 'submitted',
    support_count: 31,
    is_anonymous: false,
    created_at: '2026-03-04T08:45:00Z',
  },
  {
    id: 'e6f7a8b9-c0d1-4e2f-8a3b-4c5d6e7f8a9b',
    reference_id: 'DSB-2026-1V4W9Z',
    title: 'Community Center Bike Lockers',
    description: 'Secure lockable bicycle parking shelters for commuters.',
    category: 'Transport',
    location_text: 'Civic Plaza Community Center',
    status: 'implemented',
    support_count: 53,
    is_anonymous: true,
    created_at: '2026-02-15T16:20:00Z',
  },
];
