import { Suggestion } from './types';

export const INITIAL_SUGGESTIONS: Suggestion[] = [
  {
    id: 'sug-1',
    title: 'Hazardous Pothole on Main St. & 4th Ave',
    category: 'Roads',
    description: 'Deep pothole in the northbound lane causing vehicle damage and swerving near the pedestrian crossing.',
    neighborhood: 'Downtown District',
    status: 'Under Review',
    supportCount: 42,
    createdAt: '2 hours ago',
    isUserCreated: true,
  },
  {
    id: 'sug-2',
    title: 'Flickering High-Voltage Streetlight near Park',
    category: 'Electricity',
    description: 'The streetlight fixture at the corner of Elm and 5th has been flickering violently for three nights.',
    neighborhood: 'Westside Residential',
    status: 'Pending',
    supportCount: 19,
    createdAt: '1 day ago',
    isUserCreated: true,
  },
  {
    id: 'sug-3',
    title: 'Recycling Overflow at Oak Plaza Public Bins',
    category: 'Sanitation',
    description: 'Weekend market debris has overflowed all four sorting bins, creating litter across the walkway.',
    neighborhood: 'Oak Plaza',
    status: 'Resolved',
    supportCount: 56,
    createdAt: '3 days ago',
    officialResponse: 'Municipal sanitation team cleared bins and scheduled bi-weekly Sunday pickups.',
    isUserCreated: true,
  },
  {
    id: 'sug-4',
    title: 'Blind Intersection Crossing on Maple & 8th',
    category: 'Public Safety',
    description: 'Overgrown hedge and lack of a convex mirror make turning left hazardous for motorists and cyclists.',
    neighborhood: 'North Hill',
    status: 'Under Review',
    supportCount: 31,
    createdAt: '4 days ago',
    isUserCreated: false,
  },
  {
    id: 'sug-5',
    title: 'Storm Drain Blockage Causing Standing Water',
    category: 'Roads',
    description: 'Heavy leaf buildup has fully blocked the street gutter drain, causing knee-high puddles when raining.',
    neighborhood: 'Riverbend',
    status: 'Pending',
    supportCount: 27,
    createdAt: '5 days ago',
    isUserCreated: false,
  },
  {
    id: 'sug-6',
    title: 'Install Solar LED Beacon at School Crosswalk',
    category: 'Public Safety',
    description: 'Children crossing during morning dusk need high-visibility flashing beacons for elementary safety.',
    neighborhood: 'East Meadows',
    status: 'Resolved',
    supportCount: 88,
    createdAt: '1 week ago',
    officialResponse: 'Traffic Engineering Bureau approved and installed solar flashing signal beacon on Tuesday.',
    isUserCreated: true,
  }
];
